Repository TheAlgorithms/JavaScript, pull requests merged in 2020-10, with the labels that each got.

#385 Added StringSearch
  Search/StringSearch.js
Labels: failing npm standards, good first issue

#406 Added JSDoc documentation to some sorting functions and added TimoSort
  Sorts/TimSort.js
Labels: Changes Required

#420 Added: Sodoko Solver In DP
  Dynamic-Programming/SudokuSolver.js
Labels: failing npm standards

#521 add binary convert
  Maths/BinaryConvert.js
  Maths/test/BInaryConvert.test.js
  package-lock.json
Labels: Beginner, Changes Required, good first issue
