Repository TheAlgorithms/JavaScript, pull requests merged in 2021-09, with the labels that each got.

#679 Added BellmanFord
  Graphs/BellmanFord.js
  Graphs/test/BellmanFord.test.js
Labels: failing npm standards

#684 Added Sum of Digits Implementation
  Maths/SumOfDigits.js
  Maths/test/SumOfDigits.test.js
  package-lock.json
Labels: In Progress, Reviewed

#689 Tests for check flat case
  String/CheckFlatCase.js
  String/test/CheckFlatCase.test.js
Labels: Reviewed

#690 add QuickSortRecursive method.
  Sorts/QuickSortRecursive.js
  Sorts/QuickSortRecursive.test.js
Labels: In Progress, Algorithm, Reviewed

#692 added standard js badge in Readme.md
  README.md
Labels: enhancement, Reviewed

#693 Tests check anagrams
  String/CheckAnagram.js
  String/test/CheckAnagram.test.js
Labels: Reviewed

#696 removeValue method implemented to remove a particular node from the BST #687
  Data-Structures/Tree/BinarySearchTree.js
  package-lock.json
Labels: Reviewed

#697 Quick select tests
  Data-Structures/Array/QuickSelect.js
  Data-Structures/Array/QuickSelect.test.js
Labels: Reviewed
