Repository TheAlgorithms/JavaScript, pull requests merged in 2021-10, with the labels that each got.

#702 Added backtracking sum of subset
  Backtracking/SumOfSubset.js
  Backtracking/tests/SumOfSubset.test.js
Labels: Reviewed

#703 Dice
  String/DiceCoefficient.js
  String/test/DiceCoefficient.test.js
Labels: Reviewed

#707 Added DecimalToRoman
  Conversions/DecimalToRoman.js
  Conversions/test/DecimalToRoman.test.js
Labels: Reviewed

#711 Added ProjectEuler problem 8 with passed test cases
  Project-Euler/Problem8.js
  Project-Euler/test/Problem8.test.js
Labels: hacktoberfest

#719 Added Fisher Yates Algorithm
  Sorts/FisherYatesShuffle.js
  Sorts/test/FisherYatesShuffle.test.js
Labels: hacktoberfest

#713 Add proper test to Backtracking/Sudoku
  Backtracking/Sudoku.js
  Backtracking/tests/Sudoku.test.js
Labels: failing npm standards, Reviewed

#714 Rewrote "Rat in a maze" algorithm + added tests
  Backtracking/RatInAMaze.js
  Backtracking/tests/RatInAMaze.test.js
Labels: Reviewed

#732 Feat: Added Memoize Func
  Cache/Memoize.js
  Cache/test/Memoize.test.js
Labels: hacktoberfest

#727 Proposal: Clean up CI job a bit
  .github/workflows/UpdateDirectory.js
  .github/workflows/UpdateDirectory.mjs
  .github/workflows/ci.yml
  .github/workflows/commitAndPushDirectory.sh
  .github/workflows/nodejs.yml
  .github/workflows/update_directory_md.yml
  DIRECTORY.md
  package-lock.json
  package.json
Labels: Reviewed

#748 added Backtracking/AllCombinationsOfSizeK
  Backtracking/AllCombinationsOfSizeK.js
  Backtracking/tests/AllCombinationsOfSizeK.test.mjs
  package-lock.json
  package.json
Labels: enhancement, Algorithm, Reviewed

#738 Cycle sort tests
  Sorts/CycleSort.js
  Sorts/test/CycleSort.test.js
Labels: enhancement, Changes Required

#750 added documentation, js standard style and jest testing to kadane algorithm file.
  Dynamic-Programming/KadaneAlgo.js
  Dynamic-Programming/tests/KadaneAlgo.test.js
Labels: enhancement, Algorithm, Reviewed

#828 Add LinearSieve.js
  Maths/LinearSieve.js
  Maths/test/LinearSieve.test.js
Labels: enhancement, Algorithm, Reviewed

#827 Added bisection method
  DIRECTORY.md
  Maths/BisectionMethod.js
  Maths/test/BisectionMethod.test.js
Labels: enhancement, Algorithm, Reviewed
