Repository TheAlgorithms/JavaScript, pull requests merged in 2021-12, with the labels that each got.

#858 Add test case and enacements
  Data-Structures/Linked-List/SinglyLinkList.js
  Data-Structures/Linked-List/test/SinglyLinkList.test.js
Labels: enhancement, Reviewed

#856 Add ValidateUrl in String
  String/ValidateUrl.js
  String/test/ValidateUrl.test.js
Labels: enhancement, Algorithm, Reviewed

#861 Remove console.log from Permutation String algorithm
  Dynamic-Programming/Sliding-Window/PermutationinString.js
Labels: enhancement, Reviewed

#863 Add lower
  String/Lower.js
  String/test/Lower.test.js
Labels: enhancement, Algorithm, Reviewed

#867 Add tests and docs for the Longest Common Subsequence algorithm
  Dynamic-Programming/LongestCommonSubsequence.js
  Dynamic-Programming/tests/LongestCommonSubsequence.test.js
Labels: enhancement, Reviewed

#866 Absolute value
  Maths/Abs.js
  Maths/test/Abs.test.js
Labels: enhancement, Algorithm, Reviewed

#864 count Vowels
  String/CheckVowels.js
  String/CountVowels.js
  String/test/CountVowels.test.js
Labels: enhancement, Algorithm, Reviewed

#873 Remove duplicate `DigitSum` algorithm
  DIRECTORY.md
  Maths/DigitSum.js
  Maths/test/DigitSum.test.js
Labels: Bug, enhancement

#865 Binary Convert
  Maths/BinaryConvert.js
  Maths/test/BInaryConvert.test.js
Labels: enhancement, Algorithm, Reviewed

#874 Improve Mean method
  Maths/AverageMean.js
  Maths/test/AverageMean.test.js
Labels: enhancement, Reviewed

#875 add areaTriangleWithAllThreeSides method in Math/Area.js
  Maths/Area.js
  Maths/test/Area.test.js
Labels: enhancement, Reviewed

#872 add alphanumerical sort
  Sorts/AlphaNumericalSort.js
  Sorts/test/AlphaNumericalSort.test.js
Labels: Algorithm, Reviewed

#869 improve median
  Maths/AverageMedian.js
Labels: enhancement, Reviewed
