Repository TheAlgorithms/JavaScript, pull requests merged in 2021-05, with the labels that each got.

#599 fixed the merge implementation in MergeSort
  Sorts/MergeSort.js
Labels: Changes Required

#357 Added Matrix Exponentiation (Recursive)
  Maths/MatrixExponentiationRecursive.js
Labels: wontfix

#597 Fix Maths/IsDivisible
  Maths/IsDivisible.js
  Maths/test/IsDivisible.test.js
Labels: enhancement, failing npm standards

#243 OddEvenSort Added
  Sorts/OddEvenSort.js
Labels: wontfix
