Repository TheAlgorithms/JavaScript, pull requests merged in 2021-11, with the labels that each got.

#833 Sliding window
  .github/workflows/Codespell.yml
  Dynamic-Programming/Sliding-Window/LongestSubstringWithoutRepeatingCharacters.js
  Dynamic-Programming/Sliding-Window/PermutationinString.js
  Dynamic-Programming/Sliding-Window/test/LongestSubstringWithoutRepeatingCharacters.test.js
  Dynamic-Programming/Sliding-Window/test/PermutationinString.test.js
Labels: enhancement, Changes Required, Algorithm

#834 Removed ignored code files form codespell workflow.
  .github/workflows/Codespell.yml
  DIRECTORY.md
Labels: enhancement

#835 fixed argument data type
  Dynamic-Programming/SudokuSolver.js
Labels: enhancement, Reviewed

#839 Add TribonacciNumber in dp
  Dynamic-Programming/TribonacciNumber.js
  Dynamic-Programming/tests/TribonacciNumber.test.js
Labels: enhancement, Algorithm, Reviewed

#840 Add FibonacciNumber.js test case and update the decription of function.
  Dynamic-Programming/FibonacciNumber.js
  Dynamic-Programming/tests/FibonacciNumber.test.js
Labels: enhancement, Reviewed

#841 optamization, documantation, change return Array[bool] => Array[primes only], Add test case
  Dynamic-Programming/SieveOfEratosthenes.js
  Dynamic-Programming/tests/SieveOfEratosthenes.test.js
Labels: enhancement, Reviewed

#842 add test case and description
  Dynamic-Programming/ClimbingStairs.js
  Dynamic-Programming/tests/ClimbingStairs.test.js
Labels: enhancement, Algorithm, Reviewed

#843 add description
  Navigation/Haversine.js
Labels: enhancement, Reviewed

#845 Refactor Code and Add test case
  Data-Structures/Queue/Queue.js
  Data-Structures/Queue/test/Queue.test.js
Labels: enhancement, Reviewed

#846 fix #844
  Cache/LRUCache.js
Labels: enhancement, Reviewed

#848 Add test cases, optamization of code, and Add description of function
  Recursive/BinarySearch.js
  Recursive/test/BinarySearch.test.js
Labels: enhancement, Changes Required, Reviewed

#849 Add FindMin
  Maths/FindMin.js
  Maths/test/FindMin.test.js
Labels: enhancement, Algorithm, Reviewed

#847 Modify Graph bfs method
  Data-Structures/Graph/Graph.js
Labels: enhancement, Reviewed

#850 Graph
  Data-Structures/Graph/Graph.js
Labels: enhancement, Reviewed

#851 Add test case
  Recursive/Factorial.js
  Recursive/factorial.js
  Recursive/test/Factorial.test.js
Labels: enhancement, Reviewed

#852 Add Description and Optamization
  Sorts/QuickSort.js
Labels: enhancement, Reviewed

#854 Add test cases
  Recursive/FibonacciNumberRecursive.js
  Recursive/test/FibonacciNumberRecursive.test.js
Labels: enhancement, Reviewed

#855 Add test Case for Palindrome Recursive
  Recursive/Palindrome.js
  Recursive/test/palindrome.test.js
Labels: enhancement, Reviewed

#857 alphaNumericPlaindrome optamization
  String/AlphaNumericPalindrome.js
Labels: enhancement, Reviewed

#853 fixes: #{}
  Trees/FenwickTree.js
  Trees/test/FenwickTree.test.js
  package-lock.json
Labels: enhancement, Algorithm, Reviewed
