Repository TheAlgorithms/JavaScript, pull requests merged in 2022-06, with the labels that each got.

#1034 fix typo(change file name)
  Sorts/test/CountingSort.test.js
Labels: chore

#1036 FindSecondLargestElement: Support negative numbers
  DIRECTORY.md
  Sorts/FindSecondLargestElement.js
Labels: fix

#1037 Add test case to Find Second Largest Element Algorithm
  Sorts/test/FindSecondLargestElement.test.js
Labels: tests

#1038 Rename pigeonHoleSort.test.js to PigeonHoleSort.test.js
  Sorts/test/PigeonHoleSort.test.js
Labels: chore

#1039 Rename secondLargestElement.test.js to SecondLargestElement.test.js
  Sorts/test/SecondLargestElement.test.js
Labels: chore

#1046 Add new IsPalindrome implementation
  String/IsPalindrome.js
  String/test/IsPalindrome.test.js
Labels: algorithm

#1048 More accurate error message at `IsDivisible`
  Maths/IsDivisible.js
Labels: code quality

#1049 `Fibonacci.js` overhaul
  Maths/Fibonacci.js
  Maths/test/Fibonacci.test.js
Labels: feature, algorithm
