Repository TheAlgorithms/JavaScript, pull requests merged in 2022-07, with the labels that each got.

#1054 Fix IsPalindrome Big-O analysis
  DIRECTORY.md
  String/IsPalindrome.js
Labels: fix

#1067 Add Affine Cipher
  Ciphers/AffineCipher.js
  Ciphers/test/AffineCipher.test.js
Labels: algorithm

#1068 Fix GetEuclidGCD
  DIRECTORY.md
  Maths/GetEuclidGCD.js
Labels: algorithm, fix
