Repository TheAlgorithms/JavaScript, pull requests merged in 2022-03, with the labels that each got.

#912 Improved `Memoize` function
  Cache/Memoize.js
  Cache/test/Memoize.test.js
Labels: enhancement, Algorithm, Reviewed

#915 Add alternative implementation for `InsertionSort` and relative test.
  Sorts/InsertionSort.js
  Sorts/test/InsertionSort.test.js
Labels: enhancement, Algorithm, Reviewed

#916 Added replace method to `Upper`
  String/Upper.js
Labels: enhancement, Algorithm, Reviewed

#918 Run "style" and "test" scripts automatically when committing new changes
  .husky/pre-commit
  package-lock.json
  package.json
Labels: enhancement, Reviewed

#920 refactor `isEven` function
  Maths/IsEven.js
  Maths/test/IsEven.test.js
Labels: enhancement, Algorithm, Reviewed

#921 consistent list syntax in `CONTRIBUTING.md`
  CONTRIBUTING.md
Labels: enhancement

#922 Add testcases of BinaryCountSetBits function
  Bit-Manipulation/test/BinaryCountSetBits.test.js
Labels: enhancement, Reviewed

#923 Improved `abs` function
  Maths/Abs.js
  Maths/test/Abs.test.js
Labels: enhancement, Algorithm, Reviewed

#926 Add test case of SquareRoot function
  Maths/test/SquareRoot.test.js
Labels: enhancement, Reviewed

#929 Add test cases to ArbitraryBase, DateToDay & DateDayDifference Algorithm
  Conversions/test/ArbitraryBase.test.js
  Conversions/test/DateDayDiffernce.test.js
  Conversions/test/DateToDay.test.js
Labels: enhancement, Reviewed

#928 Add FindMinIterator algorithm
  Maths/FindMinIterator.js
  Maths/test/FindMinIterator.test.js
Labels: enhancement, Algorithm, Reviewed

#931 added @babel/eslint-parser
  package-lock.json
  package.json
Labels: Bug, Changes Required, Reviewed

#932 Add test case to DecimalToBinary,DecimalToOctal & OctToDecimal
  Conversions/test/DecimalToBinary.test.js
  Conversions/test/DecimalToOctal.test.js
  Conversions/test/OctToDecimal.test.js
Labels: enhancement, Reviewed

#935 Add test case to RGBToHex & RailwayTimeConversion algorithm
  Conversions/test/RGBToHex.test.js
  Conversions/test/RailwayTimeConversion.test.js
Labels: enhancement, Reviewed

#933 Remove duplicate helper functions in cache tests.
  Cache/test/LFUCache.test.js
  Cache/test/LRUCache.test.js
  Cache/test/Memoize.test.js
  Cache/test/cacheTest.js
Labels: enhancement, Reviewed

#939 Added new clean `LFUCache` class
  Cache/LFUCache.js
  Cache/test/LFUCache.test.js
Labels: enhancement, Reviewed

#941 Added explicit cache feature & optional parameter
  Cache/Memoize.js
  Cache/test/Memoize.test.js
Labels: enhancement, Reviewed

#907 Add `CheckExceeding` function
  String/CheckExceeding.js
  String/test/CheckExceeding.test.js
Labels: enhancement, Algorithm, Reviewed

#958 Round-trip testing for Atbash cipher
  Ciphers/test/Atbash.test.js
Labels: enhancement, Reviewed

#959 Added jest type for suggestions
  package-lock.json
  package.json
Labels: enhancement, Reviewed
