Repository TheAlgorithms/JavaScript, pull requests merged in 2022-04, with the labels that each got.

#787 Decimal Expansion
  DIRECTORY.md
  Maths/DecimalExpansion.js
  Maths/test/DecimalExpansion.test.js
Labels: enhancement, Algorithm, Reviewed

#971 Update workflow organization and environments
  .github/workflows/Ci.yml
  .github/workflows/Codespell.yml
  .github/workflows/UpdateDirectory.yml
Labels: enhancement

#985 FindLCM: Improve code readablility
  Maths/FindLcm.js
Labels: enhancement, Changes Required, Beginner, Reviewed

#987 Add proper tests for binary search
  Search/BinarySearch.js
  Search/test/BinarySearch.test.js
Labels: enhancement, on hold

#989 Format codebase with `standard.js`
  DIRECTORY.md
  Data-Structures/Tree/Trie.js
  Maths/test/EulerMethod.manual-test.js
  Sorts/TopologicalSort.js
Labels: enhancement

#992 WhileLoopFactorial: Optimize and add tests
  Maths/WhileLoopFactorial.js
  Maths/test/WhileLoopFactorial.test.js
Labels: enhancement, Reviewed

#994 EuclidGCD: add tests
  Maths/test/GetEuclidGCD.test.js
Labels: enhancement

#998 Add the Stooge Sort Algorithm
  Sorts/StoogeSort.js
  Sorts/test/StoogeSort.test.js
Labels: Algorithm, Reviewed

#991 Fix wiggle sort
  Sorts/SimplifiedWiggleSort.js
  Sorts/WiggleSort.js
  Sorts/test/SimplifiedWiggleSort.test.js
Labels: enhancement, Algorithm
