Repository TheAlgorithms/JavaScript, pull requests merged in 2022-08, with the labels that each got.

#1057 Wrapping the example matrix with outer array
  Graphs/NumberOfIslands.js
  Graphs/test/NumberOfIslands.test.js
Labels: fix

#1075 Added JugglerSequence.js
  Maths/JugglerSequence.js
  Maths/test/JugglerSequence.test.js
Labels: algorithm

#1071 Edit `Perfect{Square, Cube}`
  Maths/PerfectCube.js
  Maths/PerfectSquare.js
  Maths/test/PerfectCube.test.js
  Maths/test/PerfectSquare.test.js
Labels: feature

#1084 Bugfix AVLTree comparator
  Data-Structures/Tree/AVLTree.js
  Data-Structures/Tree/test/AVLTree.test.js
Labels: fix
