Repository TheAlgorithms/JavaScript, pull requests merged in 2022-05, with the labels that each got.

#983 Upgrade max char
  String/MaxCharacter.js
  String/test/MaxCharacter.test.js
Labels: enhancement, Reviewed

#1002 Improve pull request template
  .github/pull_request_template.md
Labels: chore

#1003 A better `README`
  README.md
Labels: chore

#1005 Improved the complexity of dequeue O(n) to O(1)
  Data-Structures/Queue/Queue.js
  Data-Structures/Queue/test/Queue.test.js
Labels: algorithm, code quality, performance

#1006 Upgraded Algorithm of alpha numeric palindrome
  .github/workflows/Ci.yml
  String/AlphaNumericPalindrome.js
  String/test/AlphaNumericPalindrome.test.js
  package-lock.json
  package.json
Labels: algorithm, code quality, documentation, tests

#1010 Find max recursion
  Maths/FindMaxRecursion.js
  Maths/test/FindMaxRecursion.test.js
Labels: algorithm, code quality

#1017 Add test case to Vigenere Cipher Algorithm
  Ciphers/test/VigenereCipher.test.js
Labels: tests

#1022 Add the Collatz Conjecture
  Maths/CollatzSequence.js
  Maths/test/CollatzSequence.test.js
Labels: algorithm

#1024 Add Twin Primes algorithm
  Maths/TwinPrime.js
  Maths/test/TwinPrime.test.js
Labels: changes required, algorithm, tests

#1026 Add testcase to AlternativeStringArrange Algorithm
  String/test/AlternativeStringArrange.test.js
Labels: tests

#1030 Add test case to palindromeRearranging Algorithm
  String/test/CheckRearrangePalindrome.test.js
Labels: tests
