Repository TheAlgorithms/JavaScript, pull requests merged in 2022-09, with the labels that each got.

#1089 fix: spellings which are making ci fail
  .github/workflows/Ci.yml
  DIRECTORY.md
  Maths/PiApproximationMonteCarlo.js
  String/CheckAnagram.js
Labels: fix

#1088 algorithm: mobius function implementation
  Maths/MobiusFunction.js
  Maths/test/MobiusFunction.test.js
Labels: algorithm

#1093 fix: factorial function
  Maths/Factorial.js
  Maths/test/Factorial.test.js
Labels: code quality

#1094 Binomial coefficient implementation
  Maths/BinomialCoefficient.js
  Maths/test/BinomialCoefficient.test.js
Labels: algorithm

#1096 algorithm: find the middle of linked-list
  Data-Structures/Linked-List/SinglyLinkedList.js
  Data-Structures/Linked-List/test/SinglyLinkedList.test.js
Labels: algorithm

#1098 feat: AVLTree 100% test coverage
  Data-Structures/Tree/test/AVLTree.test.js
Labels: tests

#1099 refactor: Cycledetection.js and added tests
  Data-Structures/Linked-List/CycleDetection.js
  Data-Structures/Linked-List/test/CycleDetection.test.js
Labels: code quality, tests

#1104 algorithm: Square free integer
  Maths/IsSquareFree.js
  Maths/test/IsSquareFree.test.js
Labels: algorithm

#1101 refactor: RotateListRight.js and added tests
  Data-Structures/Linked-List/RotateListRight.js
  Data-Structures/Linked-List/SinglyLinkedList.js
  Data-Structures/Linked-List/test/SinglyLinkedList.test.js
Labels: code quality, tests

#1102 algorithm: Iterative (and in-place) BFS for binary trees
  Trees/BreadthFirstTreeTraversal.js
  Trees/test/BreadthFirstTreeTraversal.test.js
Labels: algorithm

#1108 refactor: BFS tree algorithms
  Trees/BreadthFirstTreeTraversal.js
  Trees/test/BreadthFirstTreeTraversal.test.js
Labels: code quality
