Repository TheAlgorithms/JavaScript, pull requests merged in 2022-12, with the labels that each got.

#1266 algorithm: signum
  Maths/Signum.js
  Maths/test/Signum.test.js
Labels: algorithm

#1269 docs: fix CI and remove LGTM badges
  DIRECTORY.md
  README.md
Labels: fix, documentation

#1271 docs: improve the contributing guidelines
  CONTRIBUTING.md
Labels: documentation

#1272 docs: improve the issue forms
  .github/ISSUE_TEMPLATE/bug_report.yml
  .github/ISSUE_TEMPLATE/config.yml
  .github/ISSUE_TEMPLATE/feature_request.yml
  .github/ISSUE_TEMPLATE/other.yml
Labels: documentation
