Repository TheAlgorithms/JavaScript, pull requests merged in 2022-10, with the labels that each got.

#1109 tests: Zero One Knapsack
  Dynamic-Programming/tests/ZeroOneKnapsack.test.js
Labels: tests

#1114 tests: Levenshtein Distance (dynamic programming solution)
  CONTRIBUTING.md
  Dynamic-Programming/LevenshteinDistance.js
  Dynamic-Programming/tests/LevenshteinDistance.test.js
Labels: tests

#1135 tests: Boyer Moore Algorithm
  String/test/BoyerMoore.test.js
Labels: tests

#1120 chore: add instruction for installing dependencies
  CONTRIBUTING.md
  package-lock.json
  package.json
Labels: chore

#1127 fix: grammar mistakes in JSDoc
  Search/TernarySearch.js
Labels: beginner-friendly, chore

#1119 Add an algorithm to find length of an arc and area of the sector formed by an arc of a circle
  Maths/CircularArc.js
  Maths/test/CircularArc.test.js
Labels: algorithm

#1144 Rename to CaesarCipher
  Ciphers/CaesarCipher.js
  Ciphers/test/CaesarCipher.test.js
  Ciphers/test/CaesarsCipher.test.js
Labels: chore

#1153 dependencies: upgrade to checkout v3
  .github/workflows/Ci.yml
Labels: chore

#1132 algorithm: Log2 using bitwise operations
  Bit-Manipulation/LogTwo.js
  Bit-Manipulation/test/LogTwo.test.js
Labels: algorithm

#1125 fix: DateToDay
  Conversions/DateToDay.js
  Conversions/test/DateToDay.test.js
Labels: fix

#1162 Renamed NQueen algorithm files, variables to NQueens
  Backtracking/NQueens.js
  Backtracking/tests/NQueen.test.js
  Backtracking/tests/NQueens.test.js
Labels: chore

#1202 Updates Discord Invite Link
  README.md
Labels: chore

#1203 chore: improve the Gitpod file
  .gitpod.yml
  DIRECTORY.md
Labels: chore

#1194 tests: only test changed packages
  .github/workflows/Ci.yml
  .husky/pre-commit
  CONTRIBUTING.md
  Project-Euler/test/Problem044.test.js
  package-lock.json
  package.json
Labels: dependencies, tests, chore
