Repository TheAlgorithms/JavaScript, pull requests merged in 2022-02, with the labels that each got.

#881 Rename `SinglyLinkList` to `SinglyLinkedList`
  DIRECTORY.md
  Data-Structures/Linked-List/SinglyLinkedList.js
  Data-Structures/Linked-List/test/SinglyLinkedList.test.js
Labels: Bug

#884 binarySearch
  Recursive/BinarySearch.js
  Recursive/test/BinarySearch.test.js
Labels: enhancement, failing npm standards, Algorithm

#885 Decrease time period for marking an issue stale
  .github/stale.yml
  DIRECTORY.md
Labels: enhancement

#894 merge: Upgrade Lower function
  String/Lower.js
  String/test/Lower.test.js
Labels: enhancement, Algorithm

#898 Corrected JSdoc typo
  Maths/AverageMean.js
Labels: enhancement, Beginner

#900 replaced constructor function with es6 class syntax
  Data-Structures/Linked-List/DoublyLinkedList.js
Labels: enhancement, failing npm standards, Algorithm

#897 Algorithm to calculate the Arithmetic Geometric Mean
  Maths/ArithmeticGeometricMean.js
  Maths/test/ArithmeticGeometricMean.test.js
Labels: enhancement, Algorithm, Reviewed

#906 Improved pangram algorithm using regular expressions
  String/CheckPangram.js
  String/test/CheckPangram.test.js
Labels: enhancement, Algorithm, Reviewed
