Repository TheAlgorithms/JavaScript, pull requests merged in 2023-10, with the labels that each got.

#1399 Feat: TwoSum function created with test cases
  Maths/TwoSum.js
  Maths/test/TwoSum.test.js
Labels: hacktoberfest

#1453 Fixes-the-Grammar-Mistake
  Backtracking/GeneratePermutations.js
Labels: hacktoberfest-invalid

#1527 docs: fix typo in existing docstring (SHA256.js)
  Hashes/SHA256.js
Labels: hacktoberfest-invalid

#1566 prettier fixes & added test cases for Project Euler problem 4
  Bit-Manipulation/BinaryCountSetBits.js
  Maths/AutomorphicNumber.js
  Maths/test/AutomorphicNumber.test.js
  Project-Euler/Problem006.js
  Project-Euler/test/Problem004.test.js
  Recursive/test/BinaryEquivalent.test.js
  Search/InterpolationSearch.js
Labels: hacktoberfest, hacktoberfest-accepted

#1519 feat: Added MD5 hashing algorithm
  Hashes/MD5.js
  Hashes/tests/MD5.test.js
Labels: hacktoberfest-accepted
